In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

ModuleNotFoundError: No module named 'sklearn'

In [2]:
import os
os.getcwd()

'c:\\Users\\Lenovo\\OneDrive\\Desktop\\Kiln_test\\src'

In [5]:
data = pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\Kiln_test\data\earth.csv")
data.head()

,cycle_id,peak_temp,soak_minutes,ramp_0_573,ramp_573_peak,cooling_rate,o2_percent,load_kg,num_pieces,clay_body,moisture_pct,ambient_temp,energy_kwh,defect_rate_pct
0,1,1239,55,236,224,89,5.5,48.4,19,porcelain,2.4,32,73.1,10.53
1,2,1206,24,116,140,212,3.7,106.2,43,stoneware,1.1,40,120.6,9.30
2,3,1300,86,214,341,160,6.4,119.7,85,porcelain,2.2,11,163.5,4.71
3,4,1229,78,260,342,76,4.8,41.7,38,stoneware,4.9,17,75.1,13.16
4,5,1041,89,66,234,194,5.4,25.7,15,earthenware,3.2,28,74.5,0.00

In [6]:
## DROPPING THE DATA COLS ROW NUMBER CUSTOMERID AND SURNAME
data = data.drop(['cycle_id', 'o2_percent'], axis=1)
data

,peak_temp,soak_minutes,ramp_0_573,ramp_573_peak,cooling_rate,load_kg,num_pieces,clay_body,moisture_pct,ambient_temp,energy_kwh,defect_rate_pct
0,1239,55,236,224,89,48.4,19,porcelain,2.4,32,73.1,10.53
1,1206,24,116,140,212,106.2,43,stoneware,1.1,40,120.6,9.30
2,1300,86,214,341,160,119.7,85,porcelain,2.2,11,163.5,4.71
3,1229,78,260,342,76,41.7,38,stoneware,4.9,17,75.1,13.16
4,1041,89,66,234,194,25.7,15,earthenware,3.2,28,74.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1060,50,285,341,284,78.1,28,earthenware,5.0,10,93.7,7.14
4996,1121,92,84,304,188,60.2,27,earthenware,3.4,22,97.7,3.70
4997,1178,74,270,357,213,41.5,33,stoneware,5.2,27,60.2,12.12
4998,1212,16,260,114,69,68.5,42,stoneware,4.2,15,104.5,9.52
4999,1203,69,236,149,172,82.5,30,stoneware,1.3,29,95.1,0.00

In [ ]:
#OHE= GEO COL
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe_cb = ohe.fit_transform(data[['clay_body']])
ohe_cb

In [ ]:
ohe_cb.toarray()

In [ ]:
ohe.get_feature_names_out(["clay_body"])

In [ ]:
cb_encoded_df = pd.DataFrame(ohe_cb.toarray(), columns= ohe.get_feature_names_out(["clay_body"]))
cb_encoded_df

In [ ]:
data = pd.concat([data.drop('clay_body', axis=1), cb_encoded_df],axis=1)
data

In [ ]:
with open('ohe.pkl', 'wb') as file:
    pickle.dump(ohe, file)

In [ ]:
## dividing dataset into dependnet and independent cols
x = data.drop('energy_kwh', axis=1)
y = data['energy_kwh']

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
with open("scaler.pkl", 'wb') as file:
    pickle.dump(scaler, file)